[package]
name = "rlua"
version = "0.14.0-alpha.0"
authors = ["kyren <catherine@chucklefish.org>"]
description = "High level bindings to Lua 5.3"
repository = "https://github.com/chucklefish/rlua"
documentation = "https://docs.rs/rlua"
readme = "README.md"
keywords = ["lua"]
license = "MIT"

[badges]
travis-ci = { repository = "chucklefish/rlua", branch = "master" }

[features]
default = ["builtin-lua"]
# Builds the correct version of Lua 5.3 inside the crate. If you want to link a
# specialized version of lua into your binary, you can disable this feature to
# do that, but care must be taken.  `rlua` makes at least the following
# assumptions about the linked lua library:
#   * LUA_INTEGER is long long
#   * LUA_NUMBER as double
#   * LUA_EXTRASPACE is sizeof(void*)
#   * LUAI_MAXSTACK is 1000000
builtin-lua = ["cc"]

[dependencies]
libc = { version = "0.2" }
failure = { git = "https://github.com/rust-lang-nursery/failure", version = "1.0" }
compiletest_rs = { version = "0.3", optional = true }
rlua-derive = { version = "0.0.1", path = "./rlua-derive", optional = true }

[build-dependencies]
cc = { version = "1.0", optional = true }

[dev-dependencies]
rustyline = "1.0.0"
criterion = "0.2.0"

[[bench]]
name = "benchmark"
harness = false

[workspace]
members = ["rlua-derive"]
